External stac example
Open-EO/openeo-community-examples pull request #53
Opened 2024-09-27 06:25 UTC by Pratichhya

Included two simple examples to load stac and merge it with available collections:
* Landsat8
* Harmonized Global Biomass for 2010

2024-09-27 11:16 UTC, HansVRP commented on python/LoadExternalSTAC/LoadBiomassSTAC.ipynb
> +    "connection = openeo.connect(\"openeo.dataspace.copernicus.eu\").authenticate_oidc()"
Maybe best to start using the federated endpoint to promote it

2024-09-27 11:27 UTC, HansVRP requested changes

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "connection = openeo.connect(\"openeo.dataspace.copernicus.eu\").authenticate_oidc()"
best to promote the federated end point here

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "This example focuses on accessing external collections, so we simplify the analysis by calculating NDVI over a nearly 10-year period. Since Sentinel-2 data has only been available from 2015 onwa
In this example we will calculate the NDVI over a 10 year period. Since....

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "Let us load Landsat-8 data for a specific location over the time range of 2014-2017. We will use the `load_stac` feature to access data from an external STAC source. Be sure to specify the bands
TO load the landsat data for the targeted spatial-temporal period, we make used of....

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "Please note that `load_stac` reads data from external providers and writes it to the CDSE backend before processing. For large areas, this can lead to slower execution times and potentially high
Very good addition; maybe its good to link to the MPC documentation on the throttled connection?

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "    properties={\"platform\": lambda x: x == \"landsat-8\"},\n",
out of interest, why is this filtering needed?

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "    properties={\"platform\": lambda x: x == \"landsat-8\"},\n",
(might be good to explain to entry users)

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "nanmedian_band = xr.apply_ufunc(\n",
is it possible to perform this type of processing with openeo processes instead?

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +    "\n",
One empty line too much

2024-09-27 11:27 UTC, HansVRP commented on python/LoadExternalSTAC/LoadLandsatSTAC.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA04AAAIjCAYAAAA0vUuxAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuNSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/xnp5ZAAAACXBIWXMAAA9hAAAPYQGoP6dpAAEAAElEQVR4nOy
very good, maybe good to point out that in this case we did not harmonize the sentinel2 and landsat collection; explaining the difference in amplitude. 

There is however also a harmonized dataset on MPC

2024-09-27 11:30 UTC, HansVRP commented on python/LoadExternalSTAC/LoadBiomassSTAC.ipynb
> + "nbformat": 4,
Very cool example! I really like it! perhaps only refer to the fed endpoint again

2024-09-27 11:45 UTC, HansVRP commented
final thought; can we put all 3 load_stac examples in a single folder? That way the repo remains a bit more condensed

2024-09-27 16:54 UTC, Pratichhya commented
addressed almost all the comments except for *is it possible to perform this type of processing with openeo processes instead?* which seems possible within the UDF. However will have to inspect the final results

2024-10-10 08:27 UTC, HansVRP approved these changes

2024-10-10 08:27 UTC, merged